// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjppyeolnfekjbkvcbim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqcHB5ZW9sbmZla2pia3ZjYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDg0OTcsImV4cCI6MjA3NDQ4NDQ5N30.VuwWVdpirac7J0rSgw4zoDn4jiD3dP6MLWsUxkniSrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});